name: Deploy Backend

on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    if: >-
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.2.2

        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}

          script: |
            cd ~/Ruffl-Backend
            git fetch origin
            git reset --hard ${{ github.event.workflow_run.head_sha }}
            docker compose up -d --build
